name: trendy-trails
version: ${project.version}
author: philip2096
description: A simple to use cosmetic plugin
main: com.github.philipkoivunen.trendy_trails.TrendyTrailsPlugin
depend: [ProtocolLib]
api-version: 1.15
commands:
  trail:
permissions:
  trendytrails.trail:
    default: false
  trendytrails.trail.set:
    default: false
  trendytrails.trail.clear:
    default: false
  trendytrails.trail.reload:
    default: false