package com.github.philipkoivunen.trendytrails.constants;

public enum  MessageConstants {
    EFFECT_SET_SUCCESS,
    EFFECT_HANDLE_FAILED,
    EFFECT_REMOVED_SUCCESS,
    COLOR_NOT_FOUND,
    NO_PERMISSION,
    MISSING_ARGUMENT,
    DEFAULT_ERROR,
    CONFIGURATION_RELOADED,
    CONFIGURATION_RELOAD_FAILED,
    NO_ACTIVE_TRAIL
}
