package com.github.philipkoivunen.trendy_trails.constants;

public enum  MessageConstants {
    EFFECT_SET_SUCCESS,
    EFFECT_HANDLE_FAILED,
    EFFECT_REMOVED_SUCCESS,
    COLOR_NOT_FOUND,
    NO_PERMISSION,
    MISSING_ARGUMENT,
    DEFAULT_ERROR,
    CONFIGURATION_RELOAD_SUCCESS,
    CONFIGURATION_RELOAD_FAILURE,
    NO_ACTIVE_TRAIL
}
