name: TrendyTrails
version: 0.1.0
author: philip2096
description: testing to create a plugin
main: com.github.philipkoivunen.trendytrails.Trails
api-version: 1.13
commands:
  trail:
    aliases:
      - trail
  fox:
    aliases:
      - foxy