name: TrendyTrails
version: 0.1.3
author: philip2096
description: A simple to use cosmetic plugin
main: com.github.philipkoivunen.trendytrails.Trails
depend: [ProtocolLib]
api-version: 1.15
commands:
  trail:
    aliases:
      - trail
permissions:
  trendytrails.trail:
    default: false
  trendytrails.trail.set:
    default: false
  trendytrails.trail.clear:
    default: false
  trendytrails.trail.reload:
    default: false